
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  walletAddress: 'walletAddress',
  walletDerivationIndex: 'walletDerivationIndex',
  openrouterApiKey: 'openrouterApiKey',
  openaiApiKey: 'openaiApiKey',
  groqApiKey: 'groqApiKey',
  grokApiKey: 'grokApiKey',
  geminiApiKey: 'geminiApiKey',
  deepseekApiKey: 'deepseekApiKey',
  zaiApiKey: 'zaiApiKey',
  anthropicApiKey: 'anthropicApiKey',
  telegramId: 'telegramId',
  telegramUsername: 'telegramUsername',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AgentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  templateType: 'templateType',
  status: 'status',
  systemPrompt: 'systemPrompt',
  llmProvider: 'llmProvider',
  llmModel: 'llmModel',
  spendingLimit: 'spendingLimit',
  spendingUsed: 'spendingUsed',
  agentWalletAddress: 'agentWalletAddress',
  walletDerivationIndex: 'walletDerivationIndex',
  walletType: 'walletType',
  sessionKeyAddress: 'sessionKeyAddress',
  sessionKeyPrivateKey: 'sessionKeyPrivateKey',
  sessionContext: 'sessionContext',
  sessionExpiresAt: 'sessionExpiresAt',
  sessionPermissions: 'sessionPermissions',
  telegramBotToken: 'telegramBotToken',
  telegramChatIds: 'telegramChatIds',
  discordBotToken: 'discordBotToken',
  webhookSecret: 'webhookSecret',
  disabledSkills: 'disabledSkills',
  externalSocials: 'externalSocials',
  channels: 'channels',
  cronJobs: 'cronJobs',
  pairingCode: 'pairingCode',
  pairingCodeExpiresAt: 'pairingCodeExpiresAt',
  openclawAgentId: 'openclawAgentId',
  imageUrl: 'imageUrl',
  imageSlug: 'imageSlug',
  imageDataBase64: 'imageDataBase64',
  erc8004AgentId: 'erc8004AgentId',
  erc8004URI: 'erc8004URI',
  erc8004TxHash: 'erc8004TxHash',
  erc8004ChainId: 'erc8004ChainId',
  reputationScore: 'reputationScore',
  exported: 'exported',
  exportedAt: 'exportedAt',
  configuration: 'configuration',
  ensSubdomain: 'ensSubdomain',
  ensNode: 'ensNode',
  ensRegisteredAt: 'ensRegisteredAt',
  agentDeployedTokens: 'agentDeployedTokens',
  ownerId: 'ownerId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deployedAt: 'deployedAt'
};

exports.Prisma.ChannelBindingScalarFieldEnum = {
  id: 'id',
  agentId: 'agentId',
  userId: 'userId',
  channelType: 'channelType',
  senderIdentifier: 'senderIdentifier',
  senderName: 'senderName',
  chatIdentifier: 'chatIdentifier',
  pairingCode: 'pairingCode',
  bindingType: 'bindingType',
  isActive: 'isActive',
  pairedAt: 'pairedAt',
  lastMessageAt: 'lastMessageAt'
};

exports.Prisma.SessionMessageScalarFieldEnum = {
  id: 'id',
  bindingId: 'bindingId',
  role: 'role',
  content: 'content',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.AgentVerificationScalarFieldEnum = {
  id: 'id',
  agentId: 'agentId',
  publicKey: 'publicKey',
  encryptedPrivateKey: 'encryptedPrivateKey',
  status: 'status',
  sessionId: 'sessionId',
  challenge: 'challenge',
  humanId: 'humanId',
  agentKeyHash: 'agentKeyHash',
  agentName: 'agentName',
  swarmUrl: 'swarmUrl',
  selfxyzVerified: 'selfxyzVerified',
  selfxyzRegisteredAt: 'selfxyzRegisteredAt',
  selfAppConfig: 'selfAppConfig',
  encryptedSelfclawApiKey: 'encryptedSelfclawApiKey',
  verifiedAt: 'verifiedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.QRCodeScalarFieldEnum = {
  id: 'id',
  agentId: 'agentId',
  content: 'content',
  dataUrl: 'dataUrl',
  createdAt: 'createdAt'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  agentId: 'agentId',
  txHash: 'txHash',
  type: 'type',
  status: 'status',
  fromAddress: 'fromAddress',
  toAddress: 'toAddress',
  amount: 'amount',
  currency: 'currency',
  gasUsed: 'gasUsed',
  blockNumber: 'blockNumber',
  description: 'description',
  createdAt: 'createdAt'
};

exports.Prisma.ActivityLogScalarFieldEnum = {
  id: 'id',
  agentId: 'agentId',
  type: 'type',
  message: 'message',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.AgentTaskScalarFieldEnum = {
  id: 'id',
  agentId: 'agentId',
  userId: 'userId',
  triggerType: 'triggerType',
  tokenSymbol: 'tokenSymbol',
  conditionType: 'conditionType',
  targetValue: 'targetValue',
  baselinePrice: 'baselinePrice',
  executeAt: 'executeAt',
  cronSchedule: 'cronSchedule',
  lastExecutedAt: 'lastExecutedAt',
  actionType: 'actionType',
  actionPayload: 'actionPayload',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EnsSubdomainScalarFieldEnum = {
  id: 'id',
  name: 'name',
  fullName: 'fullName',
  node: 'node',
  ownerAddress: 'ownerAddress',
  isAgentOwned: 'isAgentOwned',
  agentId: 'agentId',
  registeredAt: 'registeredAt',
  updatedAt: 'updatedAt',
  txHash: 'txHash'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Agent: 'Agent',
  ChannelBinding: 'ChannelBinding',
  SessionMessage: 'SessionMessage',
  AgentVerification: 'AgentVerification',
  QRCode: 'QRCode',
  Transaction: 'Transaction',
  ActivityLog: 'ActivityLog',
  AgentTask: 'AgentTask',
  EnsSubdomain: 'EnsSubdomain'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
